#ifndef C__GIT_PALINDROM_IMPLEMENTATION_PALINDROM_IMPLEMENTATION_INCLUDE_STRUCTCNODE_H_
#define C__GIT_PALINDROM_IMPLEMENTATION_PALINDROM_IMPLEMENTATION_INCLUDE_STRUCTCNODE_H_
#include "stdlib"
struct CNode {
    int data;
    CNode *next;
};
#endif  // C__GIT_PALINDROM_IMPLEMENTATION_PALINDROM_IMPLEMENTATION_INCLUDE_STRUCTCNODE_H_

